### PR TITLE
Pandoc Markdown Writers

### PR DESCRIPTION
**Pull request by has2k1**
Ref: #247

In trying to get this nice and well done it has become bigger than I envisioned but I think it will be worth it.

The main source of the "scope creep" has been need to come up with a systematic way of generating markdown for pandoc elements. The benefits are Renderers do less funky string manipulations and that uniform markup is generated. This is the reason for the pandoc sub-package modelled after [module-pandoc](https://pandoc.org/lua-filters.html#module-pandoc) that underpins the lua-filters and the [pandoc](https://hackage.haskell.org/package/pandoc-types-1.23.1/docs/Text-Pandoc-Definition.html) [types](https://hackage.haskell.org/package/pandoc-types-1.23.1/docs/src/Text.Pandoc.Definition.html).

Relate to the above, I have noticed some kind of duplication/conflict in the [interlinks module](https://github.com/machow/quartodoc/blob/c4cbbea35f67ff3099009df87a7d7dfd3bb4711f/quartodoc/interlinks.py#L82-L101). I have not looked into it, but in the end this should be harmonised.

In trying to ensure that we create valid markdown markup, we should rethink the use of backticks for intermediate links created for the interlink filter. i.e. ``[title](`target`)``. As backticks are markup for code snippets, using them for a second purpose means that we create markup that may be confusing. An alternative is `[title](:target:)`.

This [gist](https://gist.github.com/has2k1/a5470984b27aee2a62b097c2df07251d) has code that you may use to test out this PR.

### CODE REVIEW

**Comment by machow** [comment]
Thanks for this heroic PR! The new `pandoc` submodule seems like a useful layer (I can see how it cleans up renderer code!). Let me know if / when I can be helpful!

Note that `quartodoc` uses [syrupy](https://github.com/tophat/syrupy) for snapshot tests, which should allow you to check bigger renderer outputs. All these [tests with the snapshot fixture](https://github.com/machow/quartodoc/blob/main/quartodoc/tests/test_renderers.py#L120) use syrupy to test rendering different things!

**Comment by machow** [comment]
Thanks for working on this--let me know if there's anything I can do to help with the plotnine docs (linking below so I can find easily). Happy to help!

https://github.com/has2k1/plotnine/pull/706

Once the plotnine docs are deployed, I'm happy to work on refactoring the renderer back into quartodoc. I think it might be a bit tricky because it inherits the base renderer (vs [this commit, which used MdRenderer](https://github.com/machow/quartodoc/pull/302/commits/59ceb471a7e27b4a87ec6b9392c33383c763e86c#diff-8d0109125275fdfb97761c4b7ba904ec6547a035387105a9283a94ee23ba2ff4)), but I don't mind spending time refactoring the common parts back into the base Renderer. This numpydoc renderer is a super great addition!

**Comment by machow** [comment]
@has2k1 I'm on board with merging in the pandoc work, and then a separate PR for the renderer, if that's useful. (We can also modify the pandoc work in the later PR as needed).

WDYT? If you're able to add tests for the pandoc module (say in `tests/test_pandoc.py`), or something similar, then seems useful to get merged!

**Comment by has2k1** [comment]
> @has2k1 I'm on board with merging in the pandoc work, and then a separate PR for the renderer, if that's useful. 

I will do that.

**Comment by has2k1** [comment]
Now,this PR only adds the pandoc module.

**Pull request merged**
