### PR TITLE
fix: do not exclude child methods on alias classes

### PR DESCRIPTION
**Pull request by machow**
Addresses #317 by ensuring we include methods defined in a class, even we are documenting an alias of that class.

### CODE REVIEW

**Comment by machow** [comment]
@has2k1 do you mind taking a look, to see if this fixes the issue for you? (Thanks for raising, it seems like a pretty serious bug).

**Comment by has2k1** [comment]
Yes this fixes the issue. It took a while to confirm as there were confounding issues that are in griffe and have been filed there.

**Comment by ecomodeller** [comment]
👍 This PR was exactly was I was looking for.

Have been scratching my head for some hours on trying to figure out why methods on my classes were not being rendered.

I can verify that it works for my examples as well. :shipit:

**Comment by ecomodeller** [comment]
Hi @machow any plans to release a new version soon of quartodoc, I use this feature and would prefer to install a numbered version instead of a git hash? 🙏

**Comment by machow** [comment]
Hey, sorry for the wait--this is now released as v0.7.3. I'm planning a round of improvements, so if you've run into any issues in the meantime, definitely let me know :)

**Pull request merged**
