### PR TITLE
add `--watch` flag to `quartodoc build`

### PR DESCRIPTION
**Pull request by hamelsmu**
- Added `--watch` command to `quartodoc build`
- Added help strings to the `quartodoc` CLI so end users can see docs for all the options when calling `quartodoc build --help`

### CODE REVIEW

**Comment by hamelsmu** [comment]
@machow are you familiar with this pydantic error?  Something about `RootModel` vs `__root__` .  I didn't change any of the data models, so I'm thinking its a dependency thing.  But not sure.  Have you seen this before?

**Comment by hamelsmu** [comment]
> @machow are you familiar with this pydantic error? Something about RootModel vs __root__ . I didn't change any of the data models, so I'm thinking its a dependency thing. But not sure. Have you seen this before?

I fixed this by setting `pydantic<2.0` 🎉  maybe something to migrate to in the future

**Review by machow — COMMENTED** [review]
Thanks for this, it looks great! I know you mentioned running into some issues with watchdog on different platforms (e.g. windows). Do you mind saying a bit about any issues you've seen / good things to look out for?

**Comment by hamelsmu** [comment]
The only issue is I think there were some cases that you couldn't install `watchdog` on every platform however it seems like it works on mac and linux currently.  We could expand CI to also test windows at some point.  I'm not sure if this is still an issue - I don't have a windows machine

**Comment by machow** [comment]
From pairing, it looks like there are two places in the docs we talk about building:

* https://pr-210--quartodoc.netlify.app/get-started/basic-building.html
* https://pr-210--quartodoc.netlify.app/get-started/overview.html#rebuilding-site

**Comment by hamelsmu** [comment]
@machow I think this PR is ready to be reviewed now.  I added the docs

**Comment by machow** [comment]
I'm going to merge, since it looks great, and the doc tweaks are pretty slight :)

**Pull request merged**
